# Generated by Django 4.1.2 on 2022-10-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Input",),
    ]
